name: Deploy pipeline

on:
  push:
    branches:
      - master

jobs:
  check_and_deploy:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix: 
        node-version: [12.x]
    
    steps:
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Checkout 
        uses: actions/checkout@v2

      # - name: Set up cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-modules-
      #       ${{ runner.os }}-

      # - name: Install packages
      #   run: npm run install:build
      
      # - name: Lint
      #   run: npm run lint
        
      # - name: Build client
      #   run: cd client && npm run build
      
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cicd-phone-example"
          heroku_email: "mikevedsted@gmail.com"
          # healthcheck: "https://cicd-phonebook.herokuapp.com//health"
          # checkstring: "ok"
          # rollbackonhealthcheckfailed: true    



